### Chapter 4

In [1]:
from pandas import Series, DataFrame

In [2]:
import pandas as pd

In [3]:
obj = Series([4,7,-5,3])

In [4]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [7]:
obj2 = Series([4,7,-5,3],index=['d','b','a','c'])

In [8]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [9]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [10]:
obj2['a']

-5

In [11]:
obj2['d']

4

In [12]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

In [13]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [14]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [15]:
obj2 *2

d     8
b    14
a   -10
c     6
dtype: int64

In [16]:
import numpy as np

In [17]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [18]:
'b' in obj2

True

In [19]:
'e' in obj2

False

In [20]:
sdata = {'Ohio':35000,'Texas':71000, 'Oregon':16000,'Utah':5000}

In [21]:
obj3 = Series(sdata)

In [22]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [23]:
states = ['California','Ohio','Oregon','Texas']

In [24]:
obj4 = Series(sdata,index = states)

In [25]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [26]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [27]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [28]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [29]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [30]:
obj4.name = 'population'

In [31]:
obj4.index.name = 'state'

In [32]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [33]:
obj.index =['Bob','Steve','Jeff','Ryan']

In [34]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [35]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],'year':[2000,2001,2002,2001,2002],'pop':[1.5,1.7,3.6,2.4,2.9]}

In [36]:
frame=DataFrame(data)

In [37]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [38]:
DataFrame(data,columns = ['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [39]:
frame2 = DataFrame(data,columns = ['year','state','pop','debt'],index = ['one','two','three','four','five'])

In [40]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [41]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [42]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [43]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [44]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [45]:
frame2['debt']=16.5

In [46]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [47]:
frame2['debt'] = np.arange(5.)

In [48]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [49]:
val = Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [50]:
frame2['debt'] = val

In [51]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [52]:
frame2['eastern'] = frame2.state == 'Ohio'

In [53]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [54]:
del frame2['eastern']

In [55]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [56]:
pop = {'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [57]:
frame3 = DataFrame(pop,index=[2000,2001,2002])

In [58]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [59]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [60]:
DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [61]:
pdata = {'Ohio':frame3['Ohio'][:-1],'Nevada':frame3['Nevada'][:2]}

In [62]:
pdata

{'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64}

In [63]:
DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [64]:
frame3.index.name = 'year'; frame3.columns.name ='state'

In [65]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [66]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [67]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

In [68]:
obj = Series(range(3),index=['a','b','c'])

In [69]:
index = obj.index

In [70]:
index

Index(['a', 'b', 'c'], dtype='object')

In [71]:
index[1:]

Index(['b', 'c'], dtype='object')

In [72]:
index = pd.Index(np.arange(3))

In [73]:
obj2 =Series([1.5,-2.5,0],index =index)

In [74]:
obj2.index is index

True

In [75]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [76]:
'Ohio' in frame3.columns

True

In [77]:
2003 in frame3.index

False

In [78]:
obj = Series([4.5,7.2,-5.3,3.6,],index=['d','b','a','c'])

In [79]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [80]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [81]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [82]:
obj.reindex(['a','b','c','d','e'],fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [83]:
obj3 = Series(['blue','purple','yellow'],index=[0,2,4])

In [84]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [85]:
frame = DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])

In [86]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [87]:
frame2 = frame.reindex(['a','b','c','d'])

In [88]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [89]:
states = ['Texas','Utah','California']

In [90]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [91]:
frame.loc[['a','b','c','d'],states]

C:\Users\jmorr\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:1418: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [92]:
obj = Series(np.arange(5.),index=['a','b','c','d','e'])

In [93]:
new_obj = obj.drop('c')

In [94]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [95]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [96]:
data = DataFrame(np.arange(16).reshape(4,4),index=['Ohio','Colorado','Utah','New York'],columns = ['one','two','three','four'])

In [97]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [98]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [99]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [100]:
data.drop(['two','four'],axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

In [126]:
obj = Series(np.arange(4.), index=['a','b','c','d'])

In [127]:
obj['b']

1.0

In [141]:
obj[1]

1.0

In [143]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [144]:
obj[['b','a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [145]:
obj[[1,3]]

b    1.0
d    3.0
dtype: float64

In [147]:
obj[obj<2]

a    0.0
b    1.0
dtype: float64

In [149]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [150]:
obj['b':'c']=5

In [151]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [152]:
data = DataFrame(np.arange(16).reshape((4,4)),index=['Ohio','Colorado','Utah','New York'],columns = ['one','two','three','four'])

In [153]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [154]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [156]:
data[['three','one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [157]:
data[:2]

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [158]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [159]:
data<5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [161]:
data[data<5]=0

In [162]:
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [163]:
data.loc['Colorado',['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [168]:
data.ix[['Colorado','Utah'],[3,0,1]]

C:\Users\jmorr\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


four  one  two
Colorado     7    0    5
Utah        11    8    9

In [171]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [172]:
data.loc[:'Utah','two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [182]:
data.ix[data.three>5,:3]

C:\Users\jmorr\AppData\Local\Continuum\anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.
C:\Users\jmorr\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:822: FutureWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#ix-indexer-is-deprecated
  retval = getattr(retval, self.name)._getitem_axis(key, axis=i)


one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [184]:
s1 = Series([7.3, -2.5,3.4,1.5],index=['a','b','c','d'])

In [185]:
s2=Series([-2.1,3.6,-1.5,4,3.1],index=['a','c','e','f','g'])

In [186]:
s1

a    7.3
b   -2.5
c    3.4
d    1.5
dtype: float64

In [187]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [188]:
s1+s2

a    5.2
b    NaN
c    7.0
d    NaN
e    NaN
f    NaN
g    NaN
dtype: float64

In [196]:
df1 = DataFrame(np.arange(9.).reshape((3,3)),columns=list('bcd'),index=['Ohio','Texas','Colorado'])

In [197]:
df2 = DataFrame(np.arange(12.).reshape((4,3)), columns= list('bde'), index=['Utah','Ohio','Texas','Oregon'])

In [198]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [199]:
df2

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [200]:
df1+df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [201]:
df1 = DataFrame(np.arange(12.).reshape((3,4)),columns=list('abcd'))

In [203]:
df2 = DataFrame(np.arange(20.).reshape((4,5)),columns=list('abcde'))

In [204]:
df1

a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [205]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [206]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [207]:
df1.add(df2,fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [208]:
df1.reindex(columns = df2.columns,fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [209]:
arr = np.arange(12.).reshape((3,4))

In [210]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [211]:
arr[0]

array([0., 1., 2., 3.])

In [212]:
arr-arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [213]:
frame = DataFrame(np.arange(12.).reshape((4,3)),columns=list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [214]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [219]:
series = frame.iloc[0]

In [220]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [221]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [222]:
series2 = Series(range(3),index=['b','e','f'])

In [223]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [224]:
series3 = frame['d']

In [225]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [226]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [227]:
frame.sub(series3,axis=0)

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [228]:
frame = DataFrame(np.random.randn(4,3),columns = list('bde'),index=['Utah','Ohio','Texas','Oregon'])

In [229]:
frame

b         d         e
Utah   -0.981515 -0.239440 -0.861885
Ohio    0.819681 -1.493516  0.881721
Texas   0.506459 -1.133138  0.479843
Oregon -2.477615  1.287018  0.094413

In [230]:
np.abs(frame)

b         d         e
Utah    0.981515  0.239440  0.861885
Ohio    0.819681  1.493516  0.881721
Texas   0.506459  1.133138  0.479843
Oregon  2.477615  1.287018  0.094413

In [234]:
f = lambda x: x.max() - x.min()

In [235]:
frame.apply(f)

b    3.297296
d    2.780534
e    1.743606
dtype: float64

In [236]:
frame.apply(f,axis = 1)

Utah      0.742076
Ohio      2.375237
Texas     1.639597
Oregon    3.764634
dtype: float64

In [237]:
def f(x):
    return Series([x.min(), x.max()],index=['min','max'])

In [241]:
frame.apply(f)

b         d         e
min -2.477615 -1.493516 -0.861885
max  0.819681  1.287018  0.881721

In [242]:
format = lambda x: '%.2f' % x

In [243]:
frame.applymap(format)

b      d      e
Utah    -0.98  -0.24  -0.86
Ohio     0.82  -1.49   0.88
Texas    0.51  -1.13   0.48
Oregon  -2.48   1.29   0.09

In [244]:
frame['e'].map(format)

Utah      -0.86
Ohio       0.88
Texas      0.48
Oregon     0.09
Name: e, dtype: object

In [245]:
obj = Series(range(4),index = ['d','a','b','c'])

In [246]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [247]:
frame = DataFrame(np.arange(8).reshape((2,4)),index = ['three','one'],columns = ['d','a','b','c'])

In [248]:
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [249]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [254]:
frame.sort_index(axis = 1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [255]:
frame.sort_index(axis=1,ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [256]:
obj = Series([4,7,-3,2])

In [258]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [259]:
obj = Series([4,np.nan,7,np.nan,-3,2])

In [264]:
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [265]:
frame = DataFrame({'b':[4,7,-3,2],'a':[0,1,0,1]})

In [266]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [268]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [269]:
frame.sort_values(by = ['a','b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [270]:
obj = Series([7,-5,7,4,2,0,4])

In [271]:
obj.rank()

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [272]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [273]:
obj.rank(ascending=False,method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [274]:
frame = DataFrame({'b':[4.3,7,-3,2],'a':[0,1,0,1],'c':[-2,5,8,-2.5]})

In [275]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [276]:
frame.rank(axis=1)

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0