### Chapter 4

In [3]:
from pandas import Series, DataFrame

In [4]:
import pandas as pd

In [5]:
obj = Series([4,7,-5,3])

In [6]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [7]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [8]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = Series([4,7,-5,3],index=['d','b','a','c'])

In [10]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [12]:
obj2['a']

-5

In [13]:
obj2['d']

4

In [14]:
obj2[['c','a','d']]

c    3
a   -5
d    4
dtype: int64

In [15]:
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [16]:
obj2[obj2>0]

d    4
b    7
c    3
dtype: int64

In [17]:
obj2 *2

d     8
b    14
a   -10
c     6
dtype: int64

In [18]:
import numpy as np

In [19]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [20]:
'b' in obj2

True

In [21]:
'e' in obj2

False

In [22]:
sdata = {'Ohio':35000,'Texas':71000, 'Oregon':16000,'Utah':5000}

In [23]:
obj3 = Series(sdata)

In [24]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [25]:
states = ['California','Ohio','Oregon','Texas']

In [26]:
obj4 = Series(sdata,index = states)

In [27]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [28]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [29]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [30]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [31]:
obj3+obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [32]:
obj4.name = 'population'

In [33]:
obj4.index.name = 'state'

In [34]:
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [35]:
obj.index =['Bob','Steve','Jeff','Ryan']

In [36]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [37]:
data = {'state':['Ohio','Ohio','Ohio','Nevada','Nevada'],'year':[2000,2001,2002,2001,2002],'pop':[1.5,1.7,3.6,2.4,2.9]}

In [38]:
frame=DataFrame(data)

In [39]:
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [40]:
DataFrame(data,columns = ['year','state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9

In [41]:
frame2 = DataFrame(data,columns = ['year','state','pop','debt'],index = ['one','two','three','four','five'])

In [42]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN

In [43]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [44]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
Name: state, dtype: object

In [45]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
Name: year, dtype: int64

In [47]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [49]:
frame2['debt']=16.5

In [50]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5

In [51]:
frame2['debt'] = np.arange(5.)

In [52]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0

In [54]:
val = Series([-1.2,-1.5,-1.7],index=['two','four','five'])

In [56]:
frame2['debt'] = val

In [57]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7

In [58]:
frame2['eastern'] = frame2.state == 'Ohio'

In [59]:
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False

In [60]:
del frame2['eastern']

In [61]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [73]:
pop = {'Nevada':{2001:2.4,2002:2.9},'Ohio':{2000:1.5,2001:1.7,2002:3.6}}

In [79]:
frame3 = DataFrame(pop,index=[2000,2001,2002])

In [80]:
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [81]:
frame3.T

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [82]:
DataFrame(pop,index=[2001,2002,2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [83]:
pdata = {'Ohio':frame3['Ohio'][:-1],'Nevada':frame3['Nevada'][:2]}

In [84]:
pdata

{'Ohio': 2000    1.5
 2001    1.7
 Name: Ohio, dtype: float64, 'Nevada': 2000    NaN
 2001    2.4
 Name: Nevada, dtype: float64}

In [85]:
DataFrame(pdata)

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [86]:
frame3.index.name = 'year'; frame3.columns.name ='state'

In [87]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [88]:
frame3.values

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [89]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7]], dtype=object)

In [90]:
obj = Series(range(3),index=['a','b','c'])

In [91]:
index = obj.index

In [92]:
index

Index(['a', 'b', 'c'], dtype='object')

In [93]:
index[1:]

Index(['b', 'c'], dtype='object')

In [97]:
index = pd.Index(np.arange(3))

In [98]:
obj2 =Series([1.5,-2.5,0],index =index)

In [101]:
obj2.index is index

True

In [102]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [103]:
'Ohio' in frame3.columns

True

In [105]:
2003 in frame3.index

False

In [107]:
obj = Series([4.5,7.2,-5.3,3.6,],index=['d','b','a','c'])

In [108]:
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [109]:
obj2 = obj.reindex(['a','b','c','d','e'])

In [110]:
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [111]:
obj.reindex(['a','b','c','d','e'],fill_value=0)

a   -5.3
b    7.2
c    3.6
d    4.5
e    0.0
dtype: float64

In [112]:
obj3 = Series(['blue','purple','yellow'],index=[0,2,4])

In [113]:
obj3.reindex(range(6),method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [114]:
frame = DataFrame(np.arange(9).reshape((3,3)),index=['a','c','d'],columns=['Ohio','Texas','California'])

In [115]:
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [117]:
frame2 = frame.reindex(['a','b','c','d'])

In [118]:
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [119]:
states = ['Texas','Utah','California']

In [120]:
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [125]:
frame.loc[['a','b','c','d'],states]

C:\Users\jmorr\AppData\Local\Continuum\anaconda3\lib\site-packages\pandas\core\indexing.py:1418: FutureWarning: 
Passing list-likes to .loc or [] with any missing label will raise
KeyError in the future, you can use .reindex() as an alternative.

See the documentation here:
https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike
  return self._getitem_tuple(key)


Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

In [126]:
obj = Series(np.arange(5.),index=['a','b','c','d','e'])

In [127]:
new_obj = obj.drop('c')

In [128]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [129]:
obj.drop(['d','c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [132]:
data = DataFrame(np.arange(16).reshape(4,4),index=['Ohio','Colorado','Utah','New York'],columns = ['one','two','three','four'])

In [133]:
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [134]:
data.drop(['Colorado','Ohio'])

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [135]:
data.drop('two',axis=1)

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [136]:
data.drop(['two','four'],axis=1)

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14